#pragma once
#include <GL/glut.h>

typedef struct {
    float u_min;
    float v_min;
    float u_max;
    float v_max;
} SpriteDef;


typedef enum {
    SPRITE_NONE,
    SPRITE_BUTTON_LEFT,
    SPRITE_BUTTON_MIDDLE,
    SPRITE_BUTTON_RIGHT,
    SPRITE_DIRT_TOP,
    SPRITE_DIRT,
    SPRITE_BROKEN_DIRT_1,
    SPRITE_BROKEN_DIRT_2,
    SPRITE_SANDSTONE_TOP,
    SPRITE_SANDSTONE,
    SPRITE_BROKEN_SANDSTONE_1,
    SPRITE_BROKEN_SANDSTONE_2,
    SPRITE_GRANITE_TOP,
    SPRITE_GRANITE,
    SPRITE_BROKEN_GRANITE_1,
    SPRITE_BROKEN_GRANITE_2,
    SPRITE_STONE_TOP,
    SPRITE_STONE,
    SPRITE_BROKEN_STONE_1,
    SPRITE_BROKEN_STONE_2,
    SPRITE_BONUS_SPEED,
    SPRITE_BONUS_SIZE,
    SPRITE_BONUS_TIME,
    SPRITE_BONUS_COUNT,
    SPRITE_BOMB,
    SPRITE_BOMB_ALT,
    SPRITE_PLAYER_1,
    SPRITE_PLAYER_2,
    SPRITE_PLAYER_3,
    SPRITE_PLAYER_4,
    SPRITE_PLAYER_5,
    SPRITE_PLAYER_6,
    SPRITE_PLAYER_7,
    SPRITE_PLAYER_8,
    SPRITE_BG_BLUE_1,
    SPRITE_BG_BLUE_12,
    SPRITE_BG_BLUE_2,
    SPRITE_BG_BLUE_23,
    SPRITE_BG_BLUE_3,
    SPRITE_BG_BLUE_34,
    SPRITE_BG_BLUE_4,
    SPRITE_BG_YELLOW_1,
    SPRITE_BG_YELLOW_12,
    SPRITE_BG_YELLOW_2,
    SPRITE_BG_YELLOW_23,
    SPRITE_BG_YELLOW_3,
    SPRITE_BG_YELLOW_34,
    SPRITE_BG_YELLOW_4,
    SPRITE_BG_PURPLE_1,
    SPRITE_BG_PURPLE_12,
    SPRITE_BG_PURPLE_2,
    SPRITE_BG_PURPLE_23,
    SPRITE_BG_PURPLE_3,
    SPRITE_BG_PURPLE_34,
    SPRITE_BG_PURPLE_4,
    SPRITE_BG_GRAY_1,
    SPRITE_BG_GRAY_12,
    SPRITE_BG_GRAY_2,
    SPRITE_BG_GRAY_23,
    SPRITE_BG_GRAY_3,
    SPRITE_BG_GRAY_34,
    SPRITE_BG_GRAY_4,
    // Explosion sprite IDs show which directions the explosion stops (U/D/L/R)
    SPRITE_EXPLOSION_ULR,
    SPRITE_EXPLOSION_UDL,
    SPRITE_EXPLOSION_UD,
    SPRITE_EXPLOSION_UDR,
    SPRITE_EXPLOSION,
    SPRITE_EXPLOSION_LR,
    SPRITE_EXPLOSION_DR,
    SPRITE_EXPLOSION_DL,
    SPRITE_EXPLOSION_D,
    SPRITE_EXPLOSION_U,
    SPRITE_EXPLOSION_DLR,
    SPRITE_EXPLOSION_UR,
    SPRITE_EXPLOSION_UL,
    SPRITE_EXPLOSION_L,
    SPRITE_EXPLOSION_R,
    SPRITE_EXPLOSION_ALT_ULR,
    SPRITE_EXPLOSION_ALT_UDL,
    SPRITE_EXPLOSION_ALT_UD,
    SPRITE_EXPLOSION_ALT_UDR,
    SPRITE_EXPLOSION_ALT,
    SPRITE_EXPLOSION_ALT_LR,
    SPRITE_EXPLOSION_ALT_DR,
    SPRITE_EXPLOSION_ALT_DL,
    SPRITE_EXPLOSION_ALT_D,
    SPRITE_EXPLOSION_ALT_U,
    SPRITE_EXPLOSION_ALT_DLR,
    SPRITE_EXPLOSION_ALT_UR,
    SPRITE_EXPLOSION_ALT_UL,
    SPRITE_EXPLOSION_ALT_L,
    SPRITE_EXPLOSION_ALT_R,
    
    SPRITE_INPUT_LEFT,
    SPRITE_INPUT_RIGHT,
    SPRITE_INPUT_MIDDLE,

    SPRITE_TEXTBOX_TOPLEFT,
    SPRITE_TEXTBOX_TOPRIGHT,
    SPRITE_TEXTBOX_TOP,
    SPRITE_TEXTBOX_BOTTOMLEFT,
    SPRITE_TEXTBOX_BOTTOMRIGHT,
    SPRITE_TEXTBOX_BOTTOM,
    SPRITE_TEXTBOX_MIDDLELEFT,
    SPRITE_TEXTBOX_MIDDLERIGHT,
    SPRITE_TEXTBOX_MIDDLE,

    // Keep adding new sprites here!
    SPRITE_COUNT,
} SpriteId;


// Initialize the BMP loader and texture
void init_sprites(void);

// Given an ID, get the UV coordinates for custom rendering
SpriteDef get_sprite_def(SpriteId id);

// Call before rendering multiple sprites (or simply use draw_sprite which does it per element)
void bind_spritesheet(void);
void unbind_spritesheet(void);

// Easily blit a sprite to the screen with its UV dimensions properly calculated
void draw_sprite(SpriteId id, float x, float y, float w, float h);

void blit_textbox(float x, float y, float width, float height);
