#include "./themes.h"

static const struct ThemedSprites THEMES[] = {
    {
        .top = SPRITE_DIRT_TOP,
        .middle = SPRITE_DIRT,
        .broken1 = SPRITE_BROKEN_DIRT_1,
        .broken2 = SPRITE_BROKEN_DIRT_2,
        .bomb = SPRITE_BOMB,
        .background1 = SPRITE_BG_BLUE_1,
        .background12 = SPRITE_BG_BLUE_12,
        .background2 = SPRITE_BG_BLUE_2,
        .background23 = SPRITE_BG_BLUE_23,
        .background3 = SPRITE_BG_BLUE_3,
        .background34 = SPRITE_BG_BLUE_34,
        .background4 = SPRITE_BG_BLUE_4,
        .explosion = {
            .ulr = SPRITE_EXPLOSION_ULR,
            .udl = SPRITE_EXPLOSION_UDL,
            .ud = SPRITE_EXPLOSION_UD,
            .udr = SPRITE_EXPLOSION_UDR,
            .none = SPRITE_EXPLOSION,
            .lr = SPRITE_EXPLOSION_LR,
            .dr = SPRITE_EXPLOSION_DR,
            .dl = SPRITE_EXPLOSION_DL,
            .d = SPRITE_EXPLOSION_D,
            .u = SPRITE_EXPLOSION_U,
            .dlr = SPRITE_EXPLOSION_DLR,
            .ur = SPRITE_EXPLOSION_UR,
            .ul = SPRITE_EXPLOSION_UL,
            .l = SPRITE_EXPLOSION_L,
            .r = SPRITE_EXPLOSION_R,
        },
    },
    {
        .top = SPRITE_SANDSTONE_TOP,
        .middle = SPRITE_SANDSTONE,
        .broken1 = SPRITE_BROKEN_SANDSTONE_1,
        .broken2 = SPRITE_BROKEN_SANDSTONE_2,
        .bomb = SPRITE_BOMB_ALT,
        .background1 = SPRITE_BG_YELLOW_1,
        .background12 = SPRITE_BG_YELLOW_12,
        .background2 = SPRITE_BG_YELLOW_2,
        .background23 = SPRITE_BG_YELLOW_23,
        .background3 = SPRITE_BG_YELLOW_3,
        .background34 = SPRITE_BG_YELLOW_34,
        .background4 = SPRITE_BG_YELLOW_4,
        .explosion = {
            .ulr = SPRITE_EXPLOSION_ALT_ULR,
            .udl = SPRITE_EXPLOSION_ALT_UDL,
            .ud = SPRITE_EXPLOSION_ALT_UD,
            .udr = SPRITE_EXPLOSION_ALT_UDR,
            .none = SPRITE_EXPLOSION_ALT,
            .lr = SPRITE_EXPLOSION_ALT_LR,
            .dr = SPRITE_EXPLOSION_ALT_DR,
            .dl = SPRITE_EXPLOSION_ALT_DL,
            .d = SPRITE_EXPLOSION_ALT_D,
            .u = SPRITE_EXPLOSION_ALT_U,
            .dlr = SPRITE_EXPLOSION_ALT_DLR,
            .ur = SPRITE_EXPLOSION_ALT_UR,
            .ul = SPRITE_EXPLOSION_ALT_UL,
            .l = SPRITE_EXPLOSION_ALT_L,
            .r = SPRITE_EXPLOSION_ALT_R,
        },
    },
    {
        .top = SPRITE_GRANITE_TOP,
        .middle = SPRITE_GRANITE,
        .broken1 = SPRITE_BROKEN_GRANITE_1,
        .broken2 = SPRITE_BROKEN_GRANITE_2,
        .bomb = SPRITE_BOMB_ALT,
        .background1 = SPRITE_BG_PURPLE_1,
        .background12 = SPRITE_BG_PURPLE_12,
        .background2 = SPRITE_BG_PURPLE_2,
        .background23 = SPRITE_BG_PURPLE_23,
        .background3 = SPRITE_BG_PURPLE_3,
        .background34 = SPRITE_BG_PURPLE_34,
        .background4 = SPRITE_BG_PURPLE_4,
        .explosion = {
            .ulr = SPRITE_EXPLOSION_ALT_ULR,
            .udl = SPRITE_EXPLOSION_ALT_UDL,
            .ud = SPRITE_EXPLOSION_ALT_UD,
            .udr = SPRITE_EXPLOSION_ALT_UDR,
            .none = SPRITE_EXPLOSION_ALT,
            .lr = SPRITE_EXPLOSION_ALT_LR,
            .dr = SPRITE_EXPLOSION_ALT_DR,
            .dl = SPRITE_EXPLOSION_ALT_DL,
            .d = SPRITE_EXPLOSION_ALT_D,
            .u = SPRITE_EXPLOSION_ALT_U,
            .dlr = SPRITE_EXPLOSION_ALT_DLR,
            .ur = SPRITE_EXPLOSION_ALT_UR,
            .ul = SPRITE_EXPLOSION_ALT_UL,
            .l = SPRITE_EXPLOSION_ALT_L,
            .r = SPRITE_EXPLOSION_ALT_R,
        },
    },
    {
        .top = SPRITE_STONE_TOP,
        .middle = SPRITE_STONE,
        .broken1 = SPRITE_BROKEN_STONE_1,
        .broken2 = SPRITE_BROKEN_STONE_2,
        .bomb = SPRITE_BOMB,
        .background1 = SPRITE_BG_GRAY_1,
        .background12 = SPRITE_BG_GRAY_12,
        .background2 = SPRITE_BG_GRAY_2,
        .background23 = SPRITE_BG_GRAY_23,
        .background3 = SPRITE_BG_GRAY_3,
        .background34 = SPRITE_BG_GRAY_34,
        .background4 = SPRITE_BG_GRAY_4,
        .explosion = {
            .ulr = SPRITE_EXPLOSION_ULR,
            .udl = SPRITE_EXPLOSION_UDL,
            .ud = SPRITE_EXPLOSION_UD,
            .udr = SPRITE_EXPLOSION_UDR,
            .none = SPRITE_EXPLOSION,
            .lr = SPRITE_EXPLOSION_LR,
            .dr = SPRITE_EXPLOSION_DR,
            .dl = SPRITE_EXPLOSION_DL,
            .d = SPRITE_EXPLOSION_D,
            .u = SPRITE_EXPLOSION_U,
            .dlr = SPRITE_EXPLOSION_DLR,
            .ur = SPRITE_EXPLOSION_UR,
            .ul = SPRITE_EXPLOSION_UL,
            .l = SPRITE_EXPLOSION_L,
            .r = SPRITE_EXPLOSION_R,
        },
    },
};

const struct ThemedSprites* get_current_theme() {
    switch (get_game_config()->theme) {
        case THEME_DIRT: return &THEMES[0];
        case THEME_SANDSTONE: return &THEMES[1];
        case THEME_GRANITE: return &THEMES[2];
        case THEME_STONE: return &THEMES[3];
        default: return &THEMES[0]; // UNREACHABLE
    }
}
