#include "./themes.h"

static const struct ThemedSprites THEMES[] = {
    {
        .top = SPRITE_DIRT_TOP,
        .middle = SPRITE_DIRT,
        .broken1 = SPRITE_BROKEN_DIRT_1,
        .broken2 = SPRITE_BROKEN_DIRT_2,
        .bomb = SPRITE_BOMB,
        .background1 = SPRITE_BG_BLUE_1,
        .background12 = SPRITE_BG_BLUE_12,
        .background2 = SPRITE_BG_BLUE_2,
        .background23 = SPRITE_BG_BLUE_23,
        .background3 = SPRITE_BG_BLUE_3,
        .background34 = SPRITE_BG_BLUE_34,
        .background4 = SPRITE_BG_BLUE_4,
        .explosion = {
            .ulr = SPRITE_EXPLOSION_ULR,
            .udl = SPRITE_EXPLOSION_UDL,
            .ud = SPRITE_EXPLOSION_UD,
            .udr = SPRITE_EXPLOSION_UDR,
            .none = SPRITE_EXPLOSION,
            .lr = SPRITE_EXPLOSION_LR,
            .dr = SPRITE_EXPLOSION_DR,
            .dl = SPRITE_EXPLOSION_DL,
            .d = SPRITE_EXPLOSION_D,
            .u = SPRITE_EXPLOSION_U,
            .dlr = SPRITE_EXPLOSION_DLR,
            .ur = SPRITE_EXPLOSION_UR,
            .ul = SPRITE_EXPLOSION_UL,
            .l = SPRITE_EXPLOSION_L,
            .r = SPRITE_EXPLOSION_R,
        },
        .game_bg = {
            .bgTL = SPRITE_BG_DIRT_TL,
            .bgTM = SPRITE_BG_DIRT_TM,
            .bgTR = SPRITE_BG_DIRT_TR,
            .bgHL = SPRITE_BG_DIRT_HL,
            .bgHM = SPRITE_BG_DIRT_HM,
            .bgHR = SPRITE_BG_DIRT_HR,
            .bgML = SPRITE_BG_DIRT_ML,
            .bgMM = SPRITE_BG_DIRT_MM,
            .bgMR = SPRITE_BG_DIRT_MR,
            .bgLL = SPRITE_BG_DIRT_LL,
            .bgLM = SPRITE_BG_DIRT_LM,
            .bgLR = SPRITE_BG_DIRT_LR,
            .bgBL = SPRITE_BG_DIRT_BL,
            .bgBM = SPRITE_BG_DIRT_BM,
            .bgBR = SPRITE_BG_DIRT_BR,
        },
    },
    {
        .top = SPRITE_SANDSTONE_TOP,
        .middle = SPRITE_SANDSTONE,
        .broken1 = SPRITE_BROKEN_SANDSTONE_1,
        .broken2 = SPRITE_BROKEN_SANDSTONE_2,
        .bomb = SPRITE_BOMB_ALT,
        .background1 = SPRITE_BG_YELLOW_1,
        .background12 = SPRITE_BG_YELLOW_12,
        .background2 = SPRITE_BG_YELLOW_2,
        .background23 = SPRITE_BG_YELLOW_23,
        .background3 = SPRITE_BG_YELLOW_3,
        .background34 = SPRITE_BG_YELLOW_34,
        .background4 = SPRITE_BG_YELLOW_4,
        .explosion = {
            .ulr = SPRITE_EXPLOSION_ALT_ULR,
            .udl = SPRITE_EXPLOSION_ALT_UDL,
            .ud = SPRITE_EXPLOSION_ALT_UD,
            .udr = SPRITE_EXPLOSION_ALT_UDR,
            .none = SPRITE_EXPLOSION_ALT,
            .lr = SPRITE_EXPLOSION_ALT_LR,
            .dr = SPRITE_EXPLOSION_ALT_DR,
            .dl = SPRITE_EXPLOSION_ALT_DL,
            .d = SPRITE_EXPLOSION_ALT_D,
            .u = SPRITE_EXPLOSION_ALT_U,
            .dlr = SPRITE_EXPLOSION_ALT_DLR,
            .ur = SPRITE_EXPLOSION_ALT_UR,
            .ul = SPRITE_EXPLOSION_ALT_UL,
            .l = SPRITE_EXPLOSION_ALT_L,
            .r = SPRITE_EXPLOSION_ALT_R,
        },
        .game_bg = {
            .bgTL = SPRITE_BG_SANDSTONE_TL,
            .bgTM = SPRITE_BG_SANDSTONE_TM,
            .bgTR = SPRITE_BG_SANDSTONE_TR,
            .bgHL = SPRITE_BG_SANDSTONE_HL,
            .bgHM = SPRITE_BG_SANDSTONE_HM,
            .bgHR = SPRITE_BG_SANDSTONE_HR,
            .bgML = SPRITE_BG_SANDSTONE_ML,
            .bgMM = SPRITE_BG_SANDSTONE_MM,
            .bgMR = SPRITE_BG_SANDSTONE_MR,
            .bgLL = SPRITE_BG_SANDSTONE_LL,
            .bgLM = SPRITE_BG_SANDSTONE_LM,
            .bgLR = SPRITE_BG_SANDSTONE_LR,
            .bgBL = SPRITE_BG_SANDSTONE_BL,
            .bgBM = SPRITE_BG_SANDSTONE_BM,
            .bgBR = SPRITE_BG_SANDSTONE_BR,
        },
    },
    {
        .top = SPRITE_GRANITE_TOP,
        .middle = SPRITE_GRANITE,
        .broken1 = SPRITE_BROKEN_GRANITE_1,
        .broken2 = SPRITE_BROKEN_GRANITE_2,
        .bomb = SPRITE_BOMB_ALT,
        .background1 = SPRITE_BG_PURPLE_1,
        .background12 = SPRITE_BG_PURPLE_12,
        .background2 = SPRITE_BG_PURPLE_2,
        .background23 = SPRITE_BG_PURPLE_23,
        .background3 = SPRITE_BG_PURPLE_3,
        .background34 = SPRITE_BG_PURPLE_34,
        .background4 = SPRITE_BG_PURPLE_4,
        .explosion = {
            .ulr = SPRITE_EXPLOSION_ALT_ULR,
            .udl = SPRITE_EXPLOSION_ALT_UDL,
            .ud = SPRITE_EXPLOSION_ALT_UD,
            .udr = SPRITE_EXPLOSION_ALT_UDR,
            .none = SPRITE_EXPLOSION_ALT,
            .lr = SPRITE_EXPLOSION_ALT_LR,
            .dr = SPRITE_EXPLOSION_ALT_DR,
            .dl = SPRITE_EXPLOSION_ALT_DL,
            .d = SPRITE_EXPLOSION_ALT_D,
            .u = SPRITE_EXPLOSION_ALT_U,
            .dlr = SPRITE_EXPLOSION_ALT_DLR,
            .ur = SPRITE_EXPLOSION_ALT_UR,
            .ul = SPRITE_EXPLOSION_ALT_UL,
            .l = SPRITE_EXPLOSION_ALT_L,
            .r = SPRITE_EXPLOSION_ALT_R,
        },
        .game_bg = {
            .bgTL = SPRITE_BG_GRANITE_TL,
            .bgTM = SPRITE_BG_GRANITE_TM,
            .bgTR = SPRITE_BG_GRANITE_TR,
            .bgHL = SPRITE_BG_GRANITE_HL,
            .bgHM = SPRITE_BG_GRANITE_HM,
            .bgHR = SPRITE_BG_GRANITE_HR,
            .bgML = SPRITE_BG_GRANITE_ML,
            .bgMM = SPRITE_BG_GRANITE_MM,
            .bgMR = SPRITE_BG_GRANITE_MR,
            .bgLL = SPRITE_BG_GRANITE_LL,
            .bgLM = SPRITE_BG_GRANITE_LM,
            .bgLR = SPRITE_BG_GRANITE_LR,
            .bgBL = SPRITE_BG_GRANITE_BL,
            .bgBM = SPRITE_BG_GRANITE_BM,
            .bgBR = SPRITE_BG_GRANITE_BR,
        },
    },
    {
        .top = SPRITE_STONE_TOP,
        .middle = SPRITE_STONE,
        .broken1 = SPRITE_BROKEN_STONE_1,
        .broken2 = SPRITE_BROKEN_STONE_2,
        .bomb = SPRITE_BOMB,
        .background1 = SPRITE_BG_GRAY_1,
        .background12 = SPRITE_BG_GRAY_12,
        .background2 = SPRITE_BG_GRAY_2,
        .background23 = SPRITE_BG_GRAY_23,
        .background3 = SPRITE_BG_GRAY_3,
        .background34 = SPRITE_BG_GRAY_34,
        .background4 = SPRITE_BG_GRAY_4,
        .explosion = {
            .ulr = SPRITE_EXPLOSION_ULR,
            .udl = SPRITE_EXPLOSION_UDL,
            .ud = SPRITE_EXPLOSION_UD,
            .udr = SPRITE_EXPLOSION_UDR,
            .none = SPRITE_EXPLOSION,
            .lr = SPRITE_EXPLOSION_LR,
            .dr = SPRITE_EXPLOSION_DR,
            .dl = SPRITE_EXPLOSION_DL,
            .d = SPRITE_EXPLOSION_D,
            .u = SPRITE_EXPLOSION_U,
            .dlr = SPRITE_EXPLOSION_DLR,
            .ur = SPRITE_EXPLOSION_UR,
            .ul = SPRITE_EXPLOSION_UL,
            .l = SPRITE_EXPLOSION_L,
            .r = SPRITE_EXPLOSION_R,
        },
        .game_bg = {
            .bgTL = SPRITE_BG_STONE_TL,
            .bgTM = SPRITE_BG_STONE_TM,
            .bgTR = SPRITE_BG_STONE_TR,
            .bgHL = SPRITE_BG_STONE_HL,
            .bgHM = SPRITE_BG_STONE_HM,
            .bgHR = SPRITE_BG_STONE_HR,
            .bgML = SPRITE_BG_STONE_ML,
            .bgMM = SPRITE_BG_STONE_MM,
            .bgMR = SPRITE_BG_STONE_MR,
            .bgLL = SPRITE_BG_STONE_LL,
            .bgLM = SPRITE_BG_STONE_LM,
            .bgLR = SPRITE_BG_STONE_LR,
            .bgBL = SPRITE_BG_STONE_BL,
            .bgBM = SPRITE_BG_STONE_BM,
            .bgBR = SPRITE_BG_STONE_BR,
        },
    },
};

const struct ThemedSprites* get_current_theme() {
    switch (get_game_config()->theme) {
        case THEME_DIRT: return &THEMES[0];
        case THEME_SANDSTONE: return &THEMES[1];
        case THEME_GRANITE: return &THEMES[2];
        case THEME_STONE: return &THEMES[3];
        default: return &THEMES[0]; // UNREACHABLE
    }
}
